backend:
  name: git-gateway
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://blog.textmylink.com"
display_url: "https://blog.textmylink.com"
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["blog"]
      - { label: "Featured Image", name: "image", widget: "image", allow_multiple: false }
      - { label: "Author", name: "author", widget: "string", default: "Daniel Schulman" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post.njk"
